### ISSUE TITLE
Wrong button sounds

### ISSUE THREAD

**Issue by GMBale** [01org/webapps-shopping-list#14]
The below code is in "js/main.js".
<pre><code> 845             self.buttonClick01Audio = new Audio();
 846             self.buttonClick01Audio.src = "./audio/ButtonClick_01.ogg";
 847             self.buttonClick02Audio = new Audio();
 848             self.buttonClick02Audio.src = "./audio/ButtonClick_01.ogg";
 849             self.buttonClick03Audio = new Audio();
 850             self.buttonClick03Audio.src = "./audio/ButtonClick_01.ogg";</code></pre>

All three audio source paths are "./audio/ButtonClick_01.ogg".
However, there are three files in "./audio/", "_01.ogg", "_02.ogg", "_03.ogg".

**Comment by davidmaxwaterman** [comment]
thanks for this.
